export const forbiddenProfiles = [
  // Autenticação e administração
  'admin',
  'login',
  'root',
  'register',
  'logout',
  'reset-password',
  'forgot-password',
  'verify-email',
  'teste',
  'testes',
  'carangola',
  'carangoladigital',
  'dashboard',
  'painel',
  'paineldecontrole',

  // Nomes reservados para institucional
  'sitemap',
  'privacy',
  'terms',
  'about',
  'contact',

  // Rotas administrativas e de configurações
  'dashboard',
  'settings',
  'support',
  'help',
  'maintenance',
  'backup',

  // Endpoints e recursos estáticos
  'api',
  'assets',
  'static',
  'public',
  'server',
  'client',

  // Nomes que poderiam colidir com perfis de usuário
  'profile',
  'profiles',
  'user',
  'users',
  'home',
  'news',
  'blog',

  // Outros caminhos específicos que você quer reservar
  'anuncios',
  'servicos',
  'feed',
  'search',
  'explore',
  'notification',
  'notifications',
  'messages',
  'imoveis',
  'inbox',
  'checkout',
  'cart',
  'payment',
  'success',
  'error',
  '404',
  '500',
  'maintenance',
  'coming',
  'coming-soon',
  'pending',
  'failure',
  'billing',
  'orders',
  'transactions',
  'report',
  'reports',
  'statistics',
  'analytics',
  'webhooks',
  'integrations',
  'plugins',
  'extensions',
  'debug',
  'health',
  'status',
  'robots.txt',
  '.well-known',
]
